### ISSUE TITLE
ゲスト：うしろのこさん

### ISSUE THREAD

**Issue by takanorip** [ogenkidesuka-fm/Topics#11]
https://twitter.com/ushiro_noko/status/1464153707361173507?s=20

**Comment by yamanoku** [comment]
@ushironoko 雑 ping
話したいこととかはこのIssueでまとめられたら

**Comment by ushironoko** [comment]
こんにちは

**Comment by yamanoku** [comment]
こんにちわ

**Comment by ushironoko** [comment]
これを喋る時間をくれ！というのは特にないので質問ベースで色々引き出していただけると…

**Comment by takanorip** [comment]
https://twitter.com/ushiro_noko/status/1465956331349704707?s=20
> 全然話と関係ないんだけど、ユーザーにデバッグさせるという面とアジャイル開発について最近もやっとするところがあったりなかったりする

**Comment by yamanoku** [comment]
> サービス横断でフロントの意思決定一緒にやっていく人ほしいな〜〜〜〜〜〜〜〜
https://twitter.com/ushiro_noko/status/1464153707361173507

- 全体のフロントエンド監督業って何をやるのか
- 技術選択をどうするか（または審美眼について）
- 意思決定をする人にほしいスキルってなんだろう

**Comment by yamanoku** [comment]
聴いてる人にも背景を知ってもらうために
うしろのこさんが今どういう役職（立ち位置）でやってるかも知れたらいいかなと思うけど
その辺はどこまで自分の口から喋ってもらえればいいかも決められたらかな @ushironoko

**Comment by yamanoku** [comment]
6日にあった[Front-End Lounge #2「フロントエンドエンジニアのキャリア」 - YouTube](https://www.youtube.com/watch?v=zw_bt_j2xW0)の話もしたいかも

俺たちは不確実性請負人だったのか、らへん

あとは各領域との協業とか…？

**Comment by ushironoko** [comment]
不確実性請負人の話今みました（遅）
話してみたさはありますね！

**Comment by takanorip** [comment]
ありがとございました！

**Comment by yamanoku** [comment]
乙！
