### ISSUE TITLE
Every Layoutの話

### ISSUE THREAD

**Issue by takanorip** [ogenkidesuka-fm/Topics#12]

**Comment by takanorip** [comment]
@yamanoku @8845musign @yuheiy こちらでPodcastの内容を詰めましょう！

**Comment by yamanoku** [comment]
翻訳作業裏話みたいなのも掘り下げてみたい。それぞれが苦労した点や作業してて学んだことなど。

**Comment by 8845musign** [comment]
- もっとエンジニアがデザインしようという話
- 翻訳作業から解き放たれて人生に活力が戻ってきた話

**Comment by 8845musign** [comment]
- 入門書の次を日本市場に出せたという話

**Comment by 8845musign** [comment]
- 監訳者の二人はEvery Layoutをどう実案件で使ってるか話

**Comment by 8845musign** [comment]
- Every Layoutはヘイドンとアンディのエッセイ
  - 主張が強い
    - 強い主張は面白い
  - 彼らにとってのベストプラクティスは僕らにとってのベストプラクティスではない
  - 書籍との良い距離の保ち方

**Comment by yamanoku** [comment]
> 翻訳作業から解き放たれて人生に活力が戻ってきた話

ワロタ（お疲れさまでした）

**Comment by yamanoku** [comment]
- レイアウトコンポーネントを作ってみている話
  - [生まれ変わったログインページにまつわるフロントエンド開発の話 - クラウドワークス エンジニアブログ](https://engineer.crowdworks.jp/entry/renewal-login)
  	- 「レイアウト制御コンポーネント」箇所
  	- `<Stack>`
