### ISSUE TITLE
所属する人をアテにする転職活動に物申したい

### ISSUE THREAD

**Issue by yamanoku** [ogenkidesuka-fm/Topics#13]
potato4d 氏の[ブログ](https://d.potato4d.me/entry/20211201-always-job-change/)を受けて思ったこと

> 〇〇と働きたい！みたいなのもしかしたら時代遅れの価値観なのかなとか
https://twitter.com/yamanoku/status/1465959141491445761

> その企業独自のドメインが大事であれば、そこで働く意義はもちろんあるんだけど、在籍している人が選定基準ってのは、なんか。
「〇〇さんが居るのが福利厚生」ってのが最近モヤるようになったのもある。
https://twitter.com/yamanoku/status/1465960344421949445

**Comment by takanorip** [comment]
すこしズレるかもしれないけど「自社のエンジニアが（自分と比べて）優秀なことが福利厚生」「自分より優秀な人と働きたい」ということについても時間があれば触れたい
