### ISSUE TITLE
「ユーザーの声を聞いてデザインしよう！」に感じる違和感

### ISSUE THREAD

**Issue by takanorip** [ogenkidesuka-fm/Topics#14]
> 「ユーザーの声を聞いてデザインしよう」という意見にいつも違和感を覚えるが、うまく説明できない
https://twitter.com/takanoripe/status/1466234203561881600

各種インタビューやリサーチの効能について

**Comment by yamanoku** [comment]
書こうと思ったらもうあった。流石です

**Comment by takanorip** [comment]
> コンサルの声は聞くのに現場の声は聞かないやつ、ユーザーの苦情があればそっちを優先するのとも似てる気がする
https://twitter.com/yamanoku/status/1467316214683009025

**Comment by yamanoku** [comment]
この辺は組織課題的なものでつぶやいたけど、デザイナーが「ユーザーの声」だけ一辺倒になるのもね、みたいなそういうところはあるかも。
ユーザーは事業ドメインを理解するための足がかりでいいと思う、みたいな。
