### ISSUE TITLE
lacoさんゲスト回

### ISSUE THREAD

**Issue by takanorip** [ogenkidesuka-fm/Topics#22]
- 収録日：2022年6月29日
- 参加者：takanorip、yamanoku、lacolaco

**Comment by yamanoku** [comment]
完全に個人的な相談？かもですが、lacolaco さんがやってるフロントエンドエキスパートチームのこととか伺いたい
https://tech.classi.jp/entry/2021/01/18/103110

自分の所属先でもチームを設立させたいので OKR の立て方とかアドバイスなど…

**Comment by lacolaco** [comment]
シンプルに、最近何やってるの？という話とか

**Comment by lacolaco** [comment]
哲学を学ぶことが仕事にいきている話

**Comment by takanorip** [comment]
- なんで哲学に興味を持ったのか
- 最近読んで面白かった哲学書
