### ISSUE TITLE
デザインエンジニアってなんだろ

### ISSUE THREAD

**Issue by takanorip** [ogenkidesuka-fm/Topics#9]
https://twitter.com/kgsi/status/1457551432714895368

- デザインエンジニアへの各社の期待値
- 個人的な感想
- UIデザイナーとグラフィックデザイナーとデザインエンジニア

**Comment by takanorip** [comment]
https://twitter.com/kgsi/status/1457551432714895368?s=20

**Comment by yamanoku** [comment]
懐かしのデザインエンジニア会（2019年）を思い出すところから…

**Comment by takanorip** [comment]
そういえばありましたね懐かしい

**Comment by takanorip** [comment]
> デザインエンジニアはUIデザイン側の不確実性を引き受ける存在なのかもなと思った
https://twitter.com/takanoripe/status/1467812885573566465

**Comment by yamanoku** [comment]
> デザインエンジニアの組織化みたいなこともやりたい
https://twitter.com/takanoripe/status/1467829795790934019?s=20

**Comment by yamanoku** [comment]
> デザインエンジニアというのは、デザイナーとしてもやれるエンジニアのことだと勘違していたのだけど、一般的にはデザインも一部できるよ、くらいの感じなのか。デザインエンジニアの「デザイン」の範囲ってかなり限定的なんだな。

https://twitter.com/niko0228/status/1474214590607405057

**Comment by yamanoku** [comment]
> UIデザインとフロントエンド開発の両方を担当頂くポジションをオープンしました。
> 
> ①UIデザインのスキルをお持ちの方にチームにフルコミットいただく ②フロントエンドの実装感覚をお持ちの方にUIデザインを担当いただく
> 
> こんな体制を実現したいと考えています。
https://twitter.com/rocky_manobi/status/1479008560990539781

[UI Designer x Frontend SWE - LAPRAS株式会社](https://herp.careers/v1/laprasinc/Huxy-b70s76i)
